In [4]:
#!pip install numpy
import numpy as np

# Pair Numpy

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [ ]:
# Crear un array 1D con 50 valores aleatorios entre 10 y 99
array = np.random.randint(10, 100, 50)
print("Array original:")
print(array)


Array original:
[47 85 36 15 21 14 22 67 64 81 72 93 83 91 14 86 19 57 18 41 43 43 64 62
 42 44 32 66 20 71 12 50 48 57 68 42 62 41 42 53 42 13 12 10 78 53 62 21
 59 57]


In [8]:
# Acceder a los elementos en posiciones múltiplos de 5 (0, 5, 10, ..., 45)
elementos_multiplos_de_5 = array[4::5]
print("\nElementos en posiciones múltiplos de 5:")
print(elementos_multiplos_de_5)


Elementos en posiciones múltiplos de 5:
[21 81 14 41 42 71 68 53 78 57]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [15]:
# Crea un array 1D con 30 valores del 1 al 20
array1 = np.random.randint(1,21,30)
print("Array original:")
array1

Array original:


array([10,  6, 14, 14,  9, 18, 20, 11, 10, 19,  7, 20, 10, 12,  6, 11, 16,
       15, 14,  5,  5, 11,  9,  4, 16, 13,  1,  9, 19, 11])

In [ ]:
# Indexación para obtener los elementos en las posiciones impares.
posiciones_impares = array1[::2]
print("Posiciones impares:")
posiciones_impares

Posiciones impares:


array([10, 14,  9, 20, 10,  7, 10,  6, 16, 14,  5,  9, 16,  1, 19])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [20]:
# Crea un array 2D de forma (4, 6) con números aleatorios decimales
array_2d = np.random.uniform(10, 100, size=(4, 6)).round(2)
print("Array 2d:")
array_2d

Array 2d:


array([[30.05, 37.36, 98.73, 56.63, 94.48, 27.62],
       [37.77, 92.71, 72.84, 65.35, 12.53, 86.9 ],
       [42.08, 41.66, 87.06, 18.6 , 30.43, 10.35],
       [22.87, 97.09, 10.19, 72.66, 71.84, 73.52]])

In [21]:
#  Accede a la última fila de la matriz
ultima_fila = array_2d[3]
print("Ultima fila:")
ultima_fila

Ultima fila:


array([22.87, 97.09, 10.19, 72.66, 71.84, 73.52])

## BONUS:

4. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [22]:
#  Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100
array_3d = np.random.randint(0, 101, size=(2, 3, 5))


In [ ]:
#  Reemplaza los elementos en posiciones múltiplos de 3 por 0.

---

## Reshape y Transpose:

> Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

>Ejercicios con transpose:

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

>Preguntas teóricas:

5. ¿Qué diferencia existe entre el reshape y el transpose?

6. ¿Y entre el transpose y el swapaxes?

---

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".